// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2JqdTtJlCC6rP5geQgYLDxU8IE15kSEg',
    appId: '1:140313943689:web:f411d5b6d4e3f38ad63058',
    messagingSenderId: '140313943689',
    projectId: 'etubm-89b9c',
    authDomain: 'etubm-89b9c.firebaseapp.com',
    storageBucket: 'etubm-89b9c.firebasestorage.app',
    measurementId: 'G-NVL9HP0JTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeBgQEYDL7GbPyIs_GImqXXE0hCwtGQm4',
    appId: '1:140313943689:android:b2d9812aeb1acbb8d63058',
    messagingSenderId: '140313943689',
    projectId: 'etubm-89b9c',
    storageBucket: 'etubm-89b9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZOAMb2OW5G9yQx1tU87WBgzN1y_2jeJI',
    appId: '1:140313943689:ios:a345c88213f03372d63058',
    messagingSenderId: '140313943689',
    projectId: 'etubm-89b9c',
    storageBucket: 'etubm-89b9c.firebasestorage.app',
    iosBundleId: 'com.example.etubm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZOAMb2OW5G9yQx1tU87WBgzN1y_2jeJI',
    appId: '1:140313943689:ios:a345c88213f03372d63058',
    messagingSenderId: '140313943689',
    projectId: 'etubm-89b9c',
    storageBucket: 'etubm-89b9c.firebasestorage.app',
    iosBundleId: 'com.example.etubm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2JqdTtJlCC6rP5geQgYLDxU8IE15kSEg',
    appId: '1:140313943689:web:e9d01705b4999b7cd63058',
    messagingSenderId: '140313943689',
    projectId: 'etubm-89b9c',
    authDomain: 'etubm-89b9c.firebaseapp.com',
    storageBucket: 'etubm-89b9c.firebasestorage.app',
    measurementId: 'G-8752NVQBTJ',
  );
}
